namespace AutoSeller.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddAllCountriesList : DbMigration
    {
        public override void Up()
        {
            Sql("SET IDENTITY_INSERT Countries on");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (5, 'AD', 'Andorra')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (6, 'AO', 'Angola')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (7, 'AI', 'Anguilla')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (8, 'AQ', 'Antarctica')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (9, 'AG', 'Antigua and Barbuda')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (10, 'AR', 'Argentina')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (11, 'AM', 'Armenia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (12, 'AW', 'Aruba')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (13, 'AU', 'Australia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (14, 'AT', 'Austria')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (15, 'AZ', 'Azerbaijan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (16, 'BS', 'Bahamas')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (17, 'BH', 'Bahrain')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (18, 'BD', 'Bangladesh')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (19, 'BB', 'Barbados')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (20, 'BY', 'Belarus')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (21, 'BE', 'Belgium')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (22, 'BZ', 'Belize')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (23, 'BJ', 'Benin')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (24, 'BM', 'Bermuda')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (25, 'BT', 'Bhutan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (26, 'BO', 'Bolivia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (27, 'BA', 'Bosnia and Herzegovina')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (28, 'BW', 'Botswana')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (29, 'BV', 'Bouvet Island')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (30, 'BR', 'Brazil')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (31, 'IO', 'British Indian Ocean Territory')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (32, 'BN', 'Brunei Darussalam')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (33, 'BG', 'Bulgaria')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (34, 'BF', 'Burkina Faso')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (35, 'BI', 'Burundi')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (36, 'KH', 'Cambodia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (37, 'CM', 'Cameroon')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (38, 'CA', 'Canada')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (39, 'CV', 'Cape Verde')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (40, 'KY', 'Cayman Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (41, 'CF', 'Central African Republic')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (42, 'TD', 'Chad')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (43, 'CL', 'Chile')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (44, 'CN', 'China')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (45, 'CX', 'Christmas Island')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (46, 'CC', 'Cocos (Keeling) Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (47, 'CO', 'Colombia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (48, 'KM', 'Comoros')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (49, 'CG', 'Congo')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (50, 'CK', 'Cook Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (51, 'CR', 'Costa Rica')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (52, 'HR', 'Croatia (Hrvatska)')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (53, 'CU', 'Cuba')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (54, 'CY', 'Cyprus')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (55, 'CZ', 'Czech Republic')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (56, 'DK', 'Denmark')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (57, 'DJ', 'Djibouti')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (58, 'DM', 'Dominica')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (59, 'DO', 'Dominican Republic')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (60, 'TP', 'East Timor')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (61, 'EC', 'Ecuador')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (62, 'EG', 'Egypt')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (63, 'SV', 'El Salvador')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (64, 'GQ', 'Equatorial Guinea')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (65, 'ER', 'Eritrea')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (66, 'EE', 'Estonia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (67, 'ET', 'Ethiopia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (68, 'FK', 'Falkland Islands (Malvinas)')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (69, 'FO', 'Faroe Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (70, 'FJ', 'Fiji')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (71, 'FI', 'Finland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (72, 'FR', 'France')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (73, 'FX', 'France, Metropolitan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (74, 'GF', 'French Guiana')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (75, 'PF', 'French Polynesia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (76, 'TF', 'French Southern Territories')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (77, 'GA', 'Gabon')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (78, 'GM', 'Gambia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (79, 'GE', 'Georgia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (80, 'GH', 'Ghana')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (81, 'GI', 'Gibraltar')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (82, 'GK', 'Guernsey')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (83, 'GR', 'Greece')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (84, 'GL', 'Greenland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (85, 'GD', 'Grenada')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (86, 'GP', 'Guadeloupe')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (87, 'GU', 'Guam')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (88, 'GT', 'Guatemala')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (89, 'GN', 'Guinea')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (90, 'GW', 'Guinea-Bissau')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (91, 'GY', 'Guyana')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (92, 'HT', 'Haiti')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (93, 'HM', 'Heard and Mc Donald Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (94, 'HN', 'Honduras')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (95, 'HK', 'Hong Kong')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (96, 'HU', 'Hungary')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (97, 'IS', 'Iceland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (98, 'IN', 'India')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (99, 'IM', 'Isle of Man')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (100, 'ID', 'Indonesia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (101, 'IR', 'Iran (Islamic Republic of)')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (102, 'IQ', 'Iraq')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (103, 'IE', 'Ireland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (104, 'IL', 'Israel')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (105, 'CI', 'Ivory Coast')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (106, 'JE', 'Jersey')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (107, 'JM', 'Jamaica')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (108, 'JP', 'Japan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (109, 'JO', 'Jordan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (110, 'KZ', 'Kazakhstan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (111, 'KE', 'Kenya')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (112, 'KI', 'Kiribati')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (113, 'KP', 'Korea, Democratic People''s Republic of')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (114, 'KR', 'Korea, Republic of')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (115, 'XK', 'Kosovo')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (116, 'KW', 'Kuwait')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (117, 'KG', 'Kyrgyzstan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (118, 'LA', 'Lao People''s Democratic Republic')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (119, 'LV', 'Latvia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (120, 'LB', 'Lebanon')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (121, 'LS', 'Lesotho')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (122, 'LR', 'Liberia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (123, 'LY', 'Libyan Arab Jamahiriya')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (124, 'LI', 'Liechtenstein')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (125, 'LT', 'Lithuania')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (126, 'LU', 'Luxembourg')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (127, 'MO', 'Macau')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (128, 'MK', 'Macedonia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (129, 'MG', 'Madagascar')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (130, 'MW', 'Malawi')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (131, 'MY', 'Malaysia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (132, 'MV', 'Maldives')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (133, 'ML', 'Mali')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (134, 'MT', 'Malta')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (135, 'MH', 'Marshall Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (136, 'MQ', 'Martinique')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (137, 'MR', 'Mauritania')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (138, 'MU', 'Mauritius')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (139, 'TY', 'Mayotte')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (140, 'MX', 'Mexico')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (141, 'FM', 'Micronesia, Federated States of')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (142, 'MD', 'Moldova, Republic of')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (143, 'MC', 'Monaco')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (144, 'MN', 'Mongolia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (145, 'ME', 'Montenegro')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (146, 'MS', 'Montserrat')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (147, 'MA', 'Morocco')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (148, 'MZ', 'Mozambique')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (149, 'MM', 'Myanmar')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (150, 'NA', 'Namibia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (151, 'NR', 'Nauru')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (152, 'NP', 'Nepal')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (153, 'NL', 'Netherlands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (154, 'AN', 'Netherlands Antilles')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (155, 'NC', 'New Caledonia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (156, 'NZ', 'New Zealand')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (157, 'NI', 'Nicaragua')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (158, 'NE', 'Niger')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (159, 'NG', 'Nigeria')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (160, 'NU', 'Niue')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (161, 'NF', 'Norfolk Island')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (162, 'MP', 'Northern Mariana Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (163, 'NO', 'Norway')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (164, 'OM', 'Oman')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (165, 'PK', 'Pakistan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (166, 'PW', 'Palau')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (167, 'PS', 'Palestine')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (168, 'PA', 'Panama')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (169, 'PG', 'Papua New Guinea')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (170, 'PY', 'Paraguay')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (171, 'PE', 'Peru')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (172, 'PH', 'Philippines')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (173, 'PN', 'Pitcairn')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (174, 'PL', 'Poland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (175, 'PT', 'Portugal')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (176, 'PR', 'Puerto Rico')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (177, 'QA', 'Qatar')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (178, 'RE', 'Reunion')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (179, 'RO', 'Romania')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (180, 'RU', 'Russian Federation')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (181, 'RW', 'Rwanda')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (182, 'KN', 'Saint Kitts and Nevis')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (183, 'LC', 'Saint Lucia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (184, 'VC', 'Saint Vincent and the Grenadines')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (185, 'WS', 'Samoa')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (186, 'SM', 'San Marino')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (187, 'ST', 'Sao Tome and Principe')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (188, 'SA', 'Saudi Arabia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (189, 'SN', 'Senegal')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (190, 'RS', 'Serbia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (191, 'SC', 'Seychelles')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (192, 'SL', 'Sierra Leone')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (193, 'SG', 'Singapore')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (194, 'SK', 'Slovakia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (195, 'SI', 'Slovenia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (196, 'SB', 'Solomon Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (197, 'SO', 'Somalia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (198, 'ZA', 'South Africa')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (199, 'GS', 'South Georgia South Sandwich Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (201, 'SS', 'South Sudan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (202, 'ES', 'Spain')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (203, 'LK', 'Sri Lanka')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (204, 'SH', 'St. Helena')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (205, 'PM', 'St. Pierre and Miquelon')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (206, 'SD', 'Sudan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (207, 'SR', 'Suriname')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (208, 'SJ', 'Svalbard and Jan Mayen Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (209, 'SZ', 'Swaziland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (210, 'SE', 'Sweden')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (211, 'CH', 'Switzerland')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (212, 'SY', 'Syrian Arab Republic')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (213, 'TW', 'Taiwan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (214, 'TJ', 'Tajikistan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (215, 'TZ', 'Tanzania, United Republic of')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (216, 'TH', 'Thailand')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (217, 'TG', 'Togo')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (218, 'TK', 'Tokelau')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (219, 'TO', 'Tonga')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (220, 'TT', 'Trinidad and Tobago')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (221, 'TN', 'Tunisia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (222, 'TR', 'Turkey')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (223, 'TM', 'Turkmenistan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (224, 'TC', 'Turks and Caicos Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (225, 'TV', 'Tuvalu')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (226, 'UG', 'Uganda')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (227, 'UA', 'Ukraine')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (228, 'AE', 'United Arab Emirates')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (229, 'GB', 'United Kingdom')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (230, 'UY', 'Uruguay')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (231, 'UZ', 'Uzbekistan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (232, 'VU', 'Vanuatu')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (233, 'VA', 'Vatican City State')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (234, 'VE', 'Venezuela')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (235, 'VN', 'Vietnam')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (236, 'VG', 'Virgin Islands (British)')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (237, 'VI', 'Virgin Islands (U.S.)')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (238, 'WF', 'Wallis and Futuna Islands')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (239, 'EH', 'Western Sahara')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (240, 'YE', 'Yemen')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (241, 'ZR', 'Zaire')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (242, 'ZM', 'Zambia')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (243, 'ZW', 'Zimbabwe')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (244, 'AF', 'Afghanistan')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (245, 'AL', 'Albania')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (246, 'DZ', 'Algeria')");
            Sql("INSERT INTO Countries(Id, CountryCode, Name) VALUES (247, 'DS', 'American Samoa')");
        }
        
        public override void Down()
        {
        }
    }
}
